# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: jFrog CLI for Artifactory
        # You may pin to the exact commit or the version.
        # uses: advancedcsg-open/action-jfrog-cli@313e1c521402e7239d3facaf9b039f01a4e95e25
        uses: jfrog/setup-jfrog-cli@v1.1.0
        with:
          # URL of Artifactory instance
          url: 'http://localhost:8081/artifactory'
          # Type of authentication to use. Must be one of username, apikey or accesstoken. Defaults to apikey
          credentials type: 'username'
          # Username for Artifactory. Must be supplied when credentials type is username
          user: 'admin'
          # Password for Artifactory. Must be supplied when credentials type is username
          password: 'admin'
          # Artifactory API Key. Must be supplied when credentials type is apikey
          #apikey: # optional
          # Artifactory access token. Must be supplied when credentials type is accesstoken
          #access token: # optional
          # Specify a working directory for the command to run in.
          #working directory: # optional, default is .
