on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "https://github.com/dipeshtripathi/artifactorydemo/blob/main/README.md"
    - name: curl
      uses: wei/curl@master
      with:
        args: -u admin:admin -T - "http://192.168.33.11/artifactory/rtifactorydemo/test/folder/for/artifactorydemoreadme"
