name: "JFrog CLI Example"
on: [push, pull_request]

jobs:
  build:
    
    runs-on: self-hosted
    container: amd64:/golang:latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_RT_DEF }}
          
      - name: Checkout
         uses: actions/checkout@v1
      - name: Build
         run:
          jfrog rt go-config --servevr-id-resolve Default-Server --repo-resolve artifactorydemo
          export CGO_ENABLED=0
          jfrog rt go build -o jfrog -ldflags '-w -extldflags "-static"' main.go --module "FFrog CLI Example"
          version=$(./jfrog -v | cut -d " " -f 3)
          echo Build JFrog CLI version $version
          jfrog rt u jfrog artifactorydemo
